如果what抛出异常，需要try catch捕获，在调用what，会无限循环。